# Postgres
POSTGRES_USER=app_user
POSTGRES_PASSWORD=app_pass
POSTGRES_DB=app_db
POSTGRES_PORT=5432

# JWT
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=30

# Порты микросервисов
AUTH_SERVICE_PORT=8001
ROOM_SERVICE_PORT=8002
CONTENT_SERVICE_PORT=8003